-- MySQL Script generated by MySQL Workbench
-- Sat Dec 24 12:18:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dcssa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dcssa` ;

-- -----------------------------------------------------
-- Schema dcssa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dcssa` DEFAULT CHARACTER SET utf8 ;
USE `dcssa` ;

-- -----------------------------------------------------
-- Table `dcssa`.`tables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dcssa`.`tables` ;

CREATE TABLE IF NOT EXISTS `dcssa`.`tables` (
  `table_number` INT NOT NULL,
  `no_of_seats` INT NOT NULL,
  `price` INT NOT NULL DEFAULT 15,
  PRIMARY KEY (`table_number`),
  UNIQUE INDEX `table_name_UNIQUE` (`table_number` ASC));


-- -----------------------------------------------------
-- Table `dcssa`.`seats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dcssa`.`seats` ;

CREATE TABLE IF NOT EXISTS `dcssa`.`seats` (
  `seat_id` INT NOT NULL AUTO_INCREMENT,
  `seat_name` VARCHAR(255) NOT NULL,
  `status` INT NOT NULL DEFAULT 0 COMMENT '0: variable, 1: reserved, 2: occupied',
  `table_number` INT NOT NULL,
  PRIMARY KEY (`seat_id`),
  UNIQUE INDEX `tabeName_UNIQUE` (`seat_name` ASC),
  INDEX `FK_tableName_idx` (`table_number` ASC),
  UNIQUE INDEX `seat_id_UNIQUE` (`seat_id` ASC),
  CONSTRAINT `FK_tableNumber`
    FOREIGN KEY (`table_number`)
    REFERENCES `dcssa`.`tables` (`table_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `dcssa`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dcssa`.`booking` ;

CREATE TABLE IF NOT EXISTS `dcssa`.`booking` (
  `booking_id` INT NOT NULL AUTO_INCREMENT,
  `seat_name` VARCHAR(255) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1: reserved (pending), 2: occupied (paid)',
  `updateTime` DATETIME NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `firstName` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `weChat` VARCHAR(255) NULL,
  UNIQUE INDEX `seat_id_UNIQUE` (`seat_name` ASC),
  PRIMARY KEY (`booking_id`),
  UNIQUE INDEX `booking_id_UNIQUE` (`booking_id` ASC),
  CONSTRAINT `FK_seatID`
    FOREIGN KEY (`seat_name`)
    REFERENCES `dcssa`.`seats` (`seat_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
